---
version: "3"
services:
  www:
    container_name: attendance-pwa
    build: .
    env_file:
      - .env
    restart: always
    ports:
      - "3000:3000"
    networks:
      - my_network

networks:
  my_network:
    external: true
